---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:

  - name: prepare repo
    image: rustdocker/rust:nightly
    commands:
      - git submodule init
      - git submodule update

  - name: check css/js formatting
    image: node:alpine
    commands:
      - npm install --save-dev --save-exact prettier
      - ./node_modules/prettier/bin-prettier.js --check assets

  - name: check rust formatting
    image: rustdocker/rust:nightly
    commands:
      - /root/.cargo/bin/cargo fmt -- --check

  - name: cargo clippy
    image: rust:1.66-buster
    commands:
      - rustup component add clippy
      - cargo clippy --workspace --tests --all-targets --all-features -- -D warnings -D deprecated -D clippy::perf -D clippy::complexity -D clippy::dbg_macro

  - name: cargo test
    image: rust:1.66-buster
    commands:
      - cargo test --workspace --no-fail-fast

  - name: nightly build
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: lemmynet/lemmybb
      tags:
        - dev
    when:
      event:
        - cron

  - name: publish release docker image
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: lemmynet/lemmybb
      auto_tag: true
    when:
      ref:
        - refs/tags/*
