version: '3.3'

services:
  lemmybb:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "127.0.0.1:1244:1244"
    environment:
      - LEMMY_BB_BACKEND=http://lemmy:8536
      - LEMMY_BB_LISTEN_ADDRESS=0.0.0.0:1244
    depends_on:
      - lemmy

  lemmy-ui:
    image: dessalines/lemmy-ui:0.16.6
    restart: always
    ports:
      - "127.0.0.1:1234:1234"
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=localhost:1234
      - LEMMY_HTTPS=false
      - LEMMY_UI_DEBUG=true
    depends_on: 
      - lemmy

  lemmy:
    image: dessalines/lemmy:0.16.6
    restart: always
    ports:
      - "127.0.0.1:8536:8536"
    environment:
      - RUST_LOG=warn
    volumes:
      - ./lemmy_config.hjson:/config/config.hjson
    depends_on:
      - pictrs
      - postgres
      - otel

  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  pictrs:
    image: asonix/pictrs:0.3.1
    restart: always
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
