version: '3.3'

services:
  lemmybb:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8701:8701"
    environment:
      - LEMMY_BB_BACKEND=http://lemmy:8536
      - LEMMY_BB_LISTEN_ADDRESS=0.0.0.0:8701
    depends_on:
      - lemmy

  lemmy-ui:
    image: dessalines/lemmy-ui:0.16.6
    restart: always
    ports:
      - "127.0.0.1:8702:1234"
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=example.com/lemmy-ui
      - LEMMY_HTTPS=true
    depends_on: 
      - lemmy

  lemmy:
    image: dessalines/lemmy:0.16.6
    restart: always
    ports:
      - "127.0.0.1:8536:8703"
    environment:
      - RUST_LOG=warn
    volumes:
      - ./lemmy.hjson:/config/config.hjson:ro
    depends_on:
      - pictrs
      - postgres

  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  pictrs:
    image: asonix/pictrs:0.3.1
    restart: always
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
