version: '3.3'

services:
  lemmybb:
    image: lemmynet/lemmybb:dev
    restart: always
    ports:
      - "127.0.0.1:8701:8701"
    environment:
      - LEMMYBB_BACKEND=http://lemmy:8536
      - LEMMYBB_LISTEN_ADDRESS=0.0.0.0:8701
      - LEMMYBB_INCREASED_RATE_LIMIT=1
    volumes:
      - ./lemmybb_categories.hjson:/app/lemmybb_categories.hjson:ro
    depends_on:
      - lemmy

  lemmy-ui:
    image: dessalines/lemmy-ui:0.16.7
    restart: always
    ports:
      - "127.0.0.1:8702:1234"
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=${LEMMY_UI_HOST}
      - LEMMY_HTTPS=true
    depends_on: 
      - lemmy

  lemmy:
    image: dessalines/lemmy:0.16.7
    restart: always
    ports:
      - "127.0.0.1:8703:8536"
    environment:
      - RUST_LOG=warn
    volumes:
      - ./lemmy.hjson:/config/config.hjson:ro
    depends_on:
      - pictrs
      - postgres

  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  pictrs:
    image: asonix/pictrs:0.3.1
    restart: always
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
